In [8]:
import pandas as pd

In [9]:
coffee = pd.read_csv("../data/raw/psd_coffee.csv")

population = pd.read_csv(
    "../data/raw/API_SP.POP.TOTL_DS2_en_csv_v2_451027.csv",
    skiprows=4
)

countries = pd.read_csv(
    "../data/raw/countries-codes.csv",
    sep=";"
)

In [10]:
print("Coffee:", coffee.shape)
print("Population:", population.shape)
print("Countries:", countries.shape)

coffee.head()

Coffee: (85937, 12)
Population: (266, 71)
Countries: (247, 11)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value
0,711100,"Coffee, Green",AL,Albania,2005,2023,6,29,Arabica Production,2,(1000 60 KG BAGS),0.0
1,711100,"Coffee, Green",AL,Albania,2005,2023,6,90,Bean Exports,2,(1000 60 KG BAGS),0.0
2,711100,"Coffee, Green",AL,Albania,2005,2023,6,58,Bean Imports,2,(1000 60 KG BAGS),80.0
3,711100,"Coffee, Green",AL,Albania,2005,2023,6,20,Beginning Stocks,2,(1000 60 KG BAGS),0.0
4,711100,"Coffee, Green",AL,Albania,2005,2023,6,125,Domestic Consumption,2,(1000 60 KG BAGS),80.0

In [11]:
print("Coffee Columns")
print(coffee.columns.tolist())

print("\nPopulation Columns")
print(population.columns.tolist())

print("\nCountries Columns")
print(countries.columns.tolist())

Coffee Columns
['Commodity_Code', 'Commodity_Description', 'Country_Code', 'Country_Name', 'Market_Year', 'Calendar_Year', 'Month', 'Attribute_ID', 'Attribute_Description', 'Unit_ID', 'Unit_Description', 'Value']

Population Columns
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', 'Unnamed: 70']

Countries Columns
['OFFICIAL LANG CODE', 'ISO2 CODE', 'ISO3 CODE', 'ONU CODE', 'IS ILOMEMBER', 'IS RECEIVING QUEST', 'LABEL EN', 'LABEL FR', 'LABEL SP', 'Geo Shape', 'geo_point_2d']

In [12]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 85937 entries, 0 to 85936
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Commodity_Code         85937 non-null  int64
 1   Commodity_Description  85937 non-null  str
 2   Country_Code           85937 non-null  str
 3   Country_Name           85937 non-null  str
 4   Market_Year            85937 non-null  int64
 5   Calendar_Year          85937 non-null  int64
 6   Month                  85937 non-null  int64
 7   Attribute_ID           85937 non-null  int64
 8   Attribute_Description  85937 non-null  str
 9   Unit_ID                85937 non-null  int64
 10  Unit_Description       85937 non-null  str
 11  Value                  85937 non-null  float64
dtypes: float64(1), int64(6), str(5)
memory usage: 12.5 MB

In [13]:
population.info()

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            264 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            264 non-null    float64
 8   1964            264 non-null    float64
 9   1965            264 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), str(4)
memory usage: 159.0 KB

In [14]:
countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OFFICIAL LANG CODE  247 non-null    str
 1   ISO2 CODE           246 non-null    str
 2   ISO3 CODE           247 non-null    str
 3   ONU CODE            247 non-null    int64
 4   IS ILOMEMBER        247 non-null    str
 5   IS RECEIVING QUEST  247 non-null    str
 6   LABEL EN            247 non-null    str
 7   LABEL FR            247 non-null    str
 8   LABEL SP            247 non-null    str
 9   Geo Shape           222 non-null    str
 10  geo_point_2d        222 non-null    str
dtypes: int64(1), str(10)
memory usage: 7.9 MB

In [15]:
# For missing values

print("Coffee Missing Values")
print(coffee.isnull().sum())

print("\nPopulation Missing Values")
print(population.isnull().sum())

print("\nCountries Missing Values")
print(countries.isnull().sum())

Coffee Missing Values
Commodity_Code           0
Commodity_Description    0
Country_Code             0
Country_Name             0
Market_Year              0
Calendar_Year            0
Month                    0
Attribute_ID             0
Attribute_Description    0
Unit_ID                  0
Unit_Description         0
Value                    0
dtype: int64

Population Missing Values
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960                2
                 ...
2022                1
2023                1
2024                1
2025              266
Unnamed: 70       266
Length: 71, dtype: int64

Countries Missing Values
OFFICIAL LANG CODE     0
ISO2 CODE              1
ISO3 CODE              0
ONU CODE               0
IS ILOMEMBER           0
IS RECEIVING QUEST     0
LABEL EN               0
LABEL FR               0
LABEL SP               0
Geo Shape             25
geo_point_2d          25
dtype: int64

In [16]:
# Checking duplicates

print("Coffee duplicates:", coffee.duplicated().sum())
print("Population duplicates:", population.duplicated().sum())
print("Countries duplicates:", countries.duplicated().sum())

Coffee duplicates: 0
Population duplicates: 0
Countries duplicates: 0

In [17]:
# =========================
# DATA CLEANING
# =========================

# Coffee
coffee_clean = coffee.copy()

# Population
population_clean = population.copy()

# Drop completely empty columns
population_clean.drop(columns=["Unnamed: 70", "2025"], inplace=True)

# Countries
countries_clean = countries.copy()

# Keep only useful columns
countries_clean = countries_clean[
    ["ISO2 CODE", "ISO3 CODE", "LABEL EN"]
]

print("Cleaning completed!")

print(coffee_clean.shape)
print(population_clean.shape)
print(countries_clean.shape)

Cleaning completed!
(85937, 12)
(266, 69)
(247, 3)

In [18]:
# Convert population data from wide to long format

population_long = population_clean.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Population"
)

# Convert Year to integer
population_long["Year"] = population_long["Year"].astype(int)

print(population_long.shape)
population_long.head()

(17290, 6)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1960,130075728.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1960,9035043.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,1960,97630925.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,1960,5231654.0

In [19]:
# =========================
# TRANSFORM POPULATION DATA
# =========================

population_long = population_clean.melt(
    id_vars=[
        "Country Name",
        "Country Code",
        "Indicator Name",
        "Indicator Code"
    ],
    var_name="Year",
    value_name="Population"
)

# Convert Year to integer
population_long["Year"] = population_long["Year"].astype(int)

print("Population Long Shape:", population_long.shape)

population_long.head()

Population Long Shape: (17290, 6)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1960,130075728.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1960,9035043.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,1960,97630925.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,1960,5231654.0

In [20]:
print(population_long.isnull().sum())

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
Year               0
Population        95
dtype: int64

In [21]:
population_long = population_long.dropna(subset=["Population"])

print(population_long.shape)

(17195, 6)

In [22]:
print(
    population_long["Year"].min(),
    population_long["Year"].max()
)

1960 2024

In [23]:
# =========================
# MERGE COFFEE + POPULATION
# =========================

coffee_population = coffee_clean.merge(
    population_long,
    left_on=["Country_Code", "Market_Year"],
    right_on=["Country Code", "Year"],
    how="left"
)

print("Merged Shape:", coffee_population.shape)

coffee_population.head()

Merged Shape: (85937, 18)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,711100,"Coffee, Green",AL,Albania,2005,2023,6,29,Arabica Production,2,(1000 60 KG BAGS),0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,711100,"Coffee, Green",AL,Albania,2005,2023,6,90,Bean Exports,2,(1000 60 KG BAGS),0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,711100,"Coffee, Green",AL,Albania,2005,2023,6,58,Bean Imports,2,(1000 60 KG BAGS),80.0,NaN,NaN,NaN,NaN,NaN,NaN
3,711100,"Coffee, Green",AL,Albania,2005,2023,6,20,Beginning Stocks,2,(1000 60 KG BAGS),0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,711100,"Coffee, Green",AL,Albania,2005,2023,6,125,Domestic Consumption,2,(1000 60 KG BAGS),80.0,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
print("Missing Population after merge:")
print(coffee_population["Population"].isnull().sum())

Missing Population after merge:
85937

In [25]:
# =========================
# ADD ISO3 CODE TO COFFEE
# =========================

coffee_iso = coffee_clean.merge(
    countries_clean,
    left_on="Country_Code",
    right_on="ISO2 CODE",
    how="left"
)

print(coffee_iso.shape)

coffee_iso.head()

(85937, 15)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value,ISO2 CODE,ISO3 CODE,LABEL EN
0,711100,"Coffee, Green",AL,Albania,2005,2023,6,29,Arabica Production,2,(1000 60 KG BAGS),0.0,AL,ALB,Albania
1,711100,"Coffee, Green",AL,Albania,2005,2023,6,90,Bean Exports,2,(1000 60 KG BAGS),0.0,AL,ALB,Albania
2,711100,"Coffee, Green",AL,Albania,2005,2023,6,58,Bean Imports,2,(1000 60 KG BAGS),80.0,AL,ALB,Albania
3,711100,"Coffee, Green",AL,Albania,2005,2023,6,20,Beginning Stocks,2,(1000 60 KG BAGS),0.0,AL,ALB,Albania
4,711100,"Coffee, Green",AL,Albania,2005,2023,6,125,Domestic Consumption,2,(1000 60 KG BAGS),80.0,AL,ALB,Albania

In [26]:
print(coffee_iso[["Country_Code", "ISO2 CODE", "ISO3 CODE"]].head(10))

  Country_Code ISO2 CODE ISO3 CODE
0           AL        AL       ALB
1           AL        AL       ALB
2           AL        AL       ALB
3           AL        AL       ALB
4           AL        AL       ALB
5           AL        AL       ALB
6           AL        AL       ALB
7           AL        AL       ALB
8           AL        AL       ALB
9           AL        AL       ALB

In [27]:
left_on = ["ISO3 CODE", "Market_Year"]
right_on = ["Country Code", "Year"]

In [28]:
# =========================
# FINAL MERGE
# =========================

final_df = coffee_iso.merge(
    population_long,
    left_on=["ISO3 CODE", "Market_Year"],
    right_on=["Country Code", "Year"],
    how="left"
)

print("Final Shape:", final_df.shape)

print("\nMissing Population:")
print(final_df["Population"].isnull().sum())

final_df.head()

Final Shape: (85937, 21)

Missing Population:
27360

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,...,Value,ISO2 CODE,ISO3 CODE,LABEL EN,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,711100,"Coffee, Green",AL,Albania,2005,2023,6,29,Arabica Production,2,...,0.0,AL,ALB,Albania,Albania,ALB,"Population, total",SP.POP.TOTL,2005.0,3011487.0
1,711100,"Coffee, Green",AL,Albania,2005,2023,6,90,Bean Exports,2,...,0.0,AL,ALB,Albania,Albania,ALB,"Population, total",SP.POP.TOTL,2005.0,3011487.0
2,711100,"Coffee, Green",AL,Albania,2005,2023,6,58,Bean Imports,2,...,80.0,AL,ALB,Albania,Albania,ALB,"Population, total",SP.POP.TOTL,2005.0,3011487.0
3,711100,"Coffee, Green",AL,Albania,2005,2023,6,20,Beginning Stocks,2,...,0.0,AL,ALB,Albania,Albania,ALB,"Population, total",SP.POP.TOTL,2005.0,3011487.0
4,711100,"Coffee, Green",AL,Albania,2005,2023,6,125,Domestic Consumption,2,...,80.0,AL,ALB,Albania,Albania,ALB,"Population, total",SP.POP.TOTL,2005.0,3011487.0

In [29]:
matched = final_df["Population"].notnull().sum()

print(f"Matched Records: {matched}")
print(f"Total Records: {len(final_df)}")
print(f"Match Rate: {matched/len(final_df)*100:.2f}%")

Matched Records: 58577
Total Records: 85937
Match Rate: 68.16%

In [30]:
# Countries that did not match with population

unmatched = final_df[final_df["Population"].isna()][
    ["Country_Name", "Country_Code", "ISO3 CODE"]
].drop_duplicates()

print("Number of unmatched countries:", len(unmatched))
unmatched.sort_values("Country_Name").head(50)

Number of unmatched countries: 93

                   Country_Name Country_Code ISO3 CODE
380                     Albania           AL       ALB
836                     Algeria           AG       ATG
2090                     Angola           AO       AGO
2546                  Argentina           AR       ARG
2850                    Armenia           AM       ARM
3306                  Australia           AS       ASM
4351                      Benin           DM       DMA
4370                    Bolivia           BL       NaN
5624     Bosnia and Herzegovina           BK       NaN
7258                     Brazil           BR       BRA
8512                    Burundi           BY       BLR
9766                   Cameroon           CM       CMR
10222                    Canada           CA       CAN
10241  Central African Republic           CT       NaN
11932                     Chile           CI       CIV
12388                     China           CH       CHE
13642                  Colombia           CO       COL
14896       Congo (Brazzaville)           CF       CAF
16150          Congo (Kinshasa)           CG       COG
16169                Costa Rica           CS       SCG
17423             Cote d'Ivoire           IV       NaN
19114                   Croatia           HR       HRV
20368                      Cuba           CU       CUB
20387        Dominican Republic           DR       NaN
22876                   Ecuador           EC       ECU
23332                     Egypt           EG       EGY
24586               El Salvador           ES       ESP
24605         Equatorial Guinea           EK       NaN
27094                  Ethiopia           ET       ETH
27113            European Union           E4       NaN
28785                     Gabon           GB       GBR
28804                   Georgia           GG       GGY
30438                     Ghana           GH       GHA
31692                 Guatemala           GT       GTM
32946                    Guinea           GU       GUM
34181                    Guyana           GY       GUY
34200                     Haiti           HA       NaN
35454                  Honduras           HO       NaN
37943                     India           IN       IND
39197                 Indonesia           ID       IDN
39558                      Iran           IR       IRN
40812                   Jamaica           JM       JAM
40831                     Japan           JA       NaN
41724                    Jordan           JO       JOR
42180                Kazakhstan           KZ       KAZ
43434                     Kenya           KE       KEN
43453              Korea, South           KS       KOS
43909                    Kosovo           KV       NaN
45106                      Laos           LA       LAO
46360                   Liberia           LI       LIE

In [68]:
coffee_clean["Country_Name"].sort_values().unique()[:30]

<ArrowStringArray>
[                 'Albania',                  'Algeria',
                   'Angola',                'Argentina',
                  'Armenia',                'Australia',
                    'Benin',                  'Bolivia',
   'Bosnia and Herzegovina',                   'Brazil',
                  'Burundi',                 'Cameroon',
                   'Canada', 'Central African Republic',
                    'Chile',                    'China',
                 'Colombia',      'Congo (Brazzaville)',
         'Congo (Kinshasa)',               'Costa Rica',
            'Cote d'Ivoire',                  'Croatia',
                     'Cuba',       'Dominican Republic',
                  'Ecuador',                    'Egypt',
              'El Salvador',        'Equatorial Guinea',
                 'Ethiopia',           'European Union']
Length: 30, dtype: str

In [88]:
countries_clean["LABEL EN"].sort_values().unique()[:30]

<ArrowStringArray>
[           'Afghanistan',                'Albania',                'Algeria',
         'American Samoa',                'Andorra',                 'Angola',
               'Anguilla',    'Antigua and Barbuda',              'Argentina',
                'Armenia',                  'Aruba',              'Australia',
                'Austria',             'Azerbaijan',                'Bahamas',
                'Bahrain',             'Bangladesh',               'Barbados',
                'Belarus',                'Belgium',                 'Belize',
                  'Benin',                'Bermuda',                 'Bhutan',
                'Bolivia', 'Bosnia and Herzegovina',               'Botswana',
                 'Brazil', 'British Virgin Islands',      'Brunei Darussalam']
Length: 30, dtype: str

In [89]:
coffee_countries = set(coffee_clean["Country_Name"].unique())
country_master = set(countries_clean["LABEL EN"].unique())

missing_names = sorted(coffee_countries - country_master)

print("Unmatched country names:", len(missing_names))
print(missing_names)

Unmatched country names: 14
['Congo (Brazzaville)', 'Congo (Kinshasa)', "Cote d'Ivoire", 'European Union', 'Iran', 'Korea, South', 'Laos', 'North Macedonia', 'Russia', 'Taiwan', 'Tanzania', 'Venezuela', 'Vietnam', 'Yemen (Sanaa)']

In [100]:
country_name_mapping = {
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Congo (Brazzaville)": "Congo",
    "Congo (Kinshasa)": "Democratic Republic of the Congo",
    "Korea, South": "South Korea",
    "Laos": "Lao People's Democratic Republic",
    "Russia": "Russian Federation",
    "Syria": "Syrian Arab Republic",
    "Turkey": "Türkiye"
}

In [117]:
# Normalize country names before joining

country_name_mapping = {
    "Congo (Brazzaville)": "Congo",
    "Congo (Kinshasa)": "Democratic Republic of the Congo",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Iran": "Iran (Islamic Republic of)",
    "Korea, South": "Republic of Korea",
    "Laos": "Lao People's Democratic Republic",
    "North Macedonia": "Macedonia",
    "Russia": "Russian Federation",
    "Taiwan": "Taiwan",
    "Tanzania": "United Republic of Tanzania",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Vietnam": "Viet Nam",
    "Yemen (Sanaa)": "Yemen"
}

coffee_clean["Country_Name_Normalized"] = (
    coffee_clean["Country_Name"]
    .replace(country_name_mapping)
)

In [126]:
coffee_country = coffee_clean.merge(
    countries_clean,
    left_on="Country_Name_Normalized",
    right_on="LABEL EN",
    how="left"
)

print(coffee_country.shape)

coffee_country.head()

(85937, 16)

,Commodity_Code,Commodity_Description,Country_Code,Country_Name,Market_Year,Calendar_Year,Month,Attribute_ID,Attribute_Description,Unit_ID,Unit_Description,Value,Country_Name_Normalized,ISO2 CODE,ISO3 CODE,LABEL EN
0,711100,"Coffee, Green",AL,Albania,2005,2023,6,29,Arabica Production,2,(1000 60 KG BAGS),0.0,Albania,AL,ALB,Albania
1,711100,"Coffee, Green",AL,Albania,2005,2023,6,90,Bean Exports,2,(1000 60 KG BAGS),0.0,Albania,AL,ALB,Albania
2,711100,"Coffee, Green",AL,Albania,2005,2023,6,58,Bean Imports,2,(1000 60 KG BAGS),80.0,Albania,AL,ALB,Albania
3,711100,"Coffee, Green",AL,Albania,2005,2023,6,20,Beginning Stocks,2,(1000 60 KG BAGS),0.0,Albania,AL,ALB,Albania
4,711100,"Coffee, Green",AL,Albania,2005,2023,6,125,Domestic Consumption,2,(1000 60 KG BAGS),80.0,Albania,AL,ALB,Albania

In [141]:
population_long["Country Name"] = population_long["Country Name"].replace({
    "Congo, Dem. Rep.": "Congo (Kinshasa)",
    "Congo, Rep.": "Congo (Brazzaville)",
    "Iran, Islamic Rep.": "Iran",
    "Korea, Rep.": "Korea, South",
    "Lao PDR": "Laos",
    "Viet Nam": "Vietnam",
    "Venezuela, RB": "Venezuela",
    "Yemen, Rep.": "Yemen",
    "Tanzania, United Rep.": "Tanzania"
})

In [148]:
final_df = coffee_country.merge(
    population_long,
    left_on=["ISO3 CODE", "Market_Year"],
    right_on=["Country Code", "Year"],
    how="left"
)

matched = final_df["Population"].notnull().sum()

print("Matched:", matched)
print("Missing:", final_df["Population"].isnull().sum())
print(f"Match Rate: {matched/len(final_df)*100:.2f}%")

Matched: 83353
Missing: 2584
Match Rate: 96.99%

In [161]:
analysis_df = final_df[[
    "Country_Name",
    "Country_Code",
    "ISO3 CODE",
    "Market_Year",
    "Attribute_Description",
    "Value",
    "Population"
]].copy()

analysis_df.head()

,Country_Name,Country_Code,ISO3 CODE,Market_Year,Attribute_Description,Value,Population
0,Albania,AL,ALB,2005,Arabica Production,0.0,3011487.0
1,Albania,AL,ALB,2005,Bean Exports,0.0,3011487.0
2,Albania,AL,ALB,2005,Bean Imports,80.0,3011487.0
3,Albania,AL,ALB,2005,Beginning Stocks,0.0,3011487.0
4,Albania,AL,ALB,2005,Domestic Consumption,80.0,3011487.0

In [173]:
print(analysis_df.shape)

analysis_df.info()

analysis_df.isnull().sum()

(85937, 7)
<class 'pandas.DataFrame'>
RangeIndex: 85937 entries, 0 to 85936
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country_Name           85937 non-null  str
 1   Country_Code           85937 non-null  str
 2   ISO3 CODE              85937 non-null  str
 3   Market_Year            85937 non-null  int64
 4   Attribute_Description  85937 non-null  str
 5   Value                  85937 non-null  float64
 6   Population             83353 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 7.0 MB

Country_Name                0
Country_Code                0
ISO3 CODE                   0
Market_Year                 0
Attribute_Description       0
Value                       0
Population               2584
dtype: int64

In [184]:
analysis_df.to_csv(
    "../data/processed/coffee_market_analysis.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [185]:
saved = pd.read_csv("../data/processed/coffee_market_analysis.csv")

print(saved.shape)

saved.head()

(85937, 7)

,Country_Name,Country_Code,ISO3 CODE,Market_Year,Attribute_Description,Value,Population
0,Albania,AL,ALB,2005,Arabica Production,0.0,3011487.0
1,Albania,AL,ALB,2005,Bean Exports,0.0,3011487.0
2,Albania,AL,ALB,2005,Bean Imports,80.0,3011487.0
3,Albania,AL,ALB,2005,Beginning Stocks,0.0,3011487.0
4,Albania,AL,ALB,2005,Domestic Consumption,80.0,3011487.0

In [194]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/coffee_market_db"
)

print("Connected Successfully!")

Connected Successfully!

In [195]:
analysis_df.to_sql(
    "coffee_market",
    engine,
    if_exists="replace",
    index=False
)

937

In [202]:
final_df[
    final_df["Population"].isna()
]["Country_Name"].value_counts()

Country_Name
Taiwan       456
Kosovo       399
Albania       19
Algeria       19
Angola        19
            ...
Venezuela     19
Vietnam       19
Yemen         19
Zambia        19
Zimbabwe      19
Name: count, Length: 93, dtype: int64

In [208]:
coffee_country["ISO3 CODE"].isnull().sum()

np.int64(0)

In [213]:
coffee_country[
    coffee_country["ISO3 CODE"].isnull()
][["Country_Name", "Country_Code"]].drop_duplicates()

Empty DataFrame
Columns: [Country_Name, Country_Code]
Index: []

In [217]:
manual_iso3 = {
    "Congo (Kinshasa)": "COD",
    "Iran": "IRN",
    "Korea, South": "KOR",
    "Laos": "LAO",
    "North Macedonia": "MKD",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Venezuela": "VEN",
    "European Union": "EUU"
}

coffee_country["ISO3 CODE"] = coffee_country["ISO3 CODE"].fillna(
    coffee_country["Country_Name"].map(manual_iso3)
)

In [220]:
coffee_country["ISO3 CODE"].isnull().sum()

np.int64(0)

In [223]:
final_df = coffee_country.merge(
    population_long,
    left_on=["ISO3 CODE", "Market_Year"],
    right_on=["Country Code", "Year"],
    how="left"
)

matched = final_df["Population"].notnull().sum()

print("Matched:", matched)
print("Missing:", final_df["Population"].isnull().sum())
print(f"Match Rate: {matched/len(final_df)*100:.2f}%")

Matched: 83353
Missing: 2584
Match Rate: 96.99%

In [224]:
final_df[
    final_df["Population"].isna()
]["Country_Name"].value_counts()

Country_Name
Taiwan       456
Kosovo       399
Albania       19
Algeria       19
Angola        19
            ...
Venezuela     19
Vietnam       19
Yemen         19
Zambia        19
Zimbabwe      19
Name: count, Length: 93, dtype: int64

In [225]:
final_df[
    final_df["Population"].isna()
][["Country_Name", "ISO3 CODE"]].drop_duplicates()

      Country_Name ISO3 CODE
380        Albania       ALB
836        Algeria       DZA
2090        Angola       AGO
2546     Argentina       ARG
2850       Armenia       ARM
...            ...       ...
80902    Venezuela       VEN
82156      Vietnam       VNM
82821        Yemen       YEM
84664       Zambia       ZMB
85918     Zimbabwe       ZWE

[93 rows x 2 columns]

In [226]:
population_long[
    population_long["Country Code"] == "TWN"
].tail()

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, Year, Population]
Index: []

In [227]:
population_long[
    population_long["Country Code"] == "XKX"
].tail()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
16221,Kosovo,XKX,"Population, total",SP.POP.TOTL,2020,1790151.0
16487,Kosovo,XKX,"Population, total",SP.POP.TOTL,2021,1786079.0
16753,Kosovo,XKX,"Population, total",SP.POP.TOTL,2022,1768096.0
17019,Kosovo,XKX,"Population, total",SP.POP.TOTL,2023,1682668.0
17285,Kosovo,XKX,"Population, total",SP.POP.TOTL,2024,1594353.0

In [228]:
sorted(final_df["Market_Year"].unique())

[np.int64(1960),
 np.int64(1961),
 np.int64(1962),
 np.int64(1963),
 np.int64(1964),
 np.int64(1965),
 np.int64(1966),
 np.int64(1967),
 np.int64(1968),
 np.int64(1969),
 np.int64(1970),
 np.int64(1971),
 np.int64(1972),
 np.int64(1973),
 np.int64(1974),
 np.int64(1975),
 np.int64(1976),
 np.int64(1977),
 np.int64(1978),
 np.int64(1979),
 np.int64(1980),
 np.int64(1981),
 np.int64(1982),
 np.int64(1983),
 np.int64(1984),
 np.int64(1985),
 np.int64(1986),
 np.int64(1987),
 np.int64(1988),
 np.int64(1989),
 np.int64(1990),
 np.int64(1991),
 np.int64(1992),
 np.int64(1993),
 np.int64(1994),
 np.int64(1995),
 np.int64(1996),
 np.int64(1997),
 np.int64(1998),
 np.int64(1999),
 np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025)]

In [229]:
population_long[
    population_long["Country Code"] == "TWN"
].tail()

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, Year, Population]
Index: []

In [230]:
population_long[
    population_long["Country Code"] == "XKX"
].tail()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
16221,Kosovo,XKX,"Population, total",SP.POP.TOTL,2020,1790151.0
16487,Kosovo,XKX,"Population, total",SP.POP.TOTL,2021,1786079.0
16753,Kosovo,XKX,"Population, total",SP.POP.TOTL,2022,1768096.0
17019,Kosovo,XKX,"Population, total",SP.POP.TOTL,2023,1682668.0
17285,Kosovo,XKX,"Population, total",SP.POP.TOTL,2024,1594353.0

In [231]:
final_df[
    (final_df["Market_Year"] == 2025) &
    (final_df["Population"].isna())
][["Country_Name","ISO3 CODE"]].drop_duplicates()

      Country_Name ISO3 CODE
380        Albania       ALB
836        Algeria       DZA
2090        Angola       AGO
2546     Argentina       ARG
2850       Armenia       ARM
...            ...       ...
80902    Venezuela       VEN
82156      Vietnam       VNM
82821        Yemen       YEM
84664       Zambia       ZMB
85918     Zimbabwe       ZWE

[93 rows x 2 columns]

In [232]:
manual_iso3 = {
    "Congo (Kinshasa)": "COD",
    "Iran": "IRN",
    "Korea, South": "KOR",
    "Laos": "LAO",
    "North Macedonia": "MKD",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Venezuela": "VEN",
    "European Union": "EUU",
    "Kosovo": "XKX"
}

In [233]:
matched = final_df["Population"].notnull().sum()

print("Matched:", matched)
print("Missing:", final_df["Population"].isnull().sum())
print(f"Match Rate: {matched/len(final_df)*100:.2f}%")

Matched: 83353
Missing: 2584
Match Rate: 96.99%